server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:postgresql://localhost:5433/cartao
#    username: cartao
#    password: cartao

  application:
    name: cartoes-ms
#  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-local.xml
  sql:
    init:
      continue-on-error: true

# h2 http://localhost:9080/h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dbteste
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

